spinnaker/rosco

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/rush/health/RushHealthIndicator.groovy

Will help avoid the initial stack-trace when rush and rosco are starting up at the same time.
@spinnaker/google-reviewers please review.

Set initial interval of rush health ping to 5 minutes.

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/RedisBackedBakeStore.groovy

With this change, each Rosco instance will only query for status updates for its own incomplete bakes.

Scope incomplete bakes to specific Rosco instance.

---

rosco-web/config/packer/install_packages.sh

We have seen failing package installs with amazon linux reported as successful bakes.
This makes the install packages script fail on errors.

Fail the build if there is an error installing packages

---

rosco-web/config/packer/aws-chroot.json
rosco-web/config/packer/install_packages.sh

When services are started on install, sometimes the bake fails because its unable to umount the disk:
` Stderr: umount: /mnt/packer-amazon-chroot-volumes/xvdg/dev: device is busy.`
https://www.packer.io/docs/builders/amazon-chroot.html look at gotchas at the end.
The reason this is done in install_packages.sh and not in the template is because of support for non debian based distros.

Dont start services when installing packages on debian based machines

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactory.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactorySpec.groovy
rosco-web/config/rosco.yml
rosco-web/rosco-web.gradle

This makes packer run as sudo if it is a aws-chroot build. There is a corresponding pull request to the spinnaker repo to add the spinnaker user to sudoers https://github.com/spinnaker/spinnaker/pull/816.
mock script to test with:
```
#!/bin/bash
echo "Running mock"
env
echo "sleep"
sleep 5
echo "done sleeping"
echo "i am"
whoami
echo "sleep"
sleep 30
```
output of mock script:
```
Running mock
SHELL=/bin/sh
TERM=linux
USER=root
SUDO_USER=spinnaker
SUDO_UID=1001
USERNAME=root
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
SUDO_COMMAND=/usr/local/bin/packer build -color=false -var aws_region=us-west-2 -var aws_ssh_username=ubuntu -var aws_instance_type=t2.micro -var aws_source_ami=ami-3d50120d -var …
```

Use sudo when running aws-chroot builder

---

rosco-web/config/packer/aws-chroot.json

Repository that contains white spaces (e.g. a deb-s3 style repository such as http://repository trusty main) causes an issue during Packer execution.
This is an example of the error.
amazon-chroot: trusty: 1: trusty: Syntax error: Unterminated quoted string

Use single quotes to handle repository

---

rosco-web/config/packer/install_packages.sh

This behavior is consitent with the debian one. Also yum correctly fail (also aborting the build)
if the package he's trying to install cannot be installed

Force yum to preserve package installation order

---

rosco-web/config/rosco.yml

Following up on a comment from:
https://github.com/kenzanlabs/spinnaker-terraform/blob/master/docs/AWS.md
This PR updates AWS AMI's to the latest. It adds a comment link to the source for AMI info:
https://cloud-images.ubuntu.com/locator/ec2/
Finally, it adds support for the us-west-1 region mentioned in the spinnaker-terraform docs above.

Add support for us-west-1. Comment that images are placeholders.

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactory.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactorySpec.groovy

This patch is a step forward in correct handling multiple packages. With this patch if a FullQualifiedPackageName get passed in the
package list it get parsed no matter the position (before it only happened for the first one).
Also, the first package keep its importance of potential determining the ami-name or the Appversion if correctly parsed
This is related to: https://github.com/spinnaker/orca/pull/800 : packages can come down in any order

Parse a FQPN at any position in the package list

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy

This PR address the following issue: Given two bakes with the same ami-name but different installed package(s), the bakeKey should be different, otherwise a rebake is required to bake it again (also the ami-suffix is not part of the bakeKey).
This is very evident when baking from the Bake stage of a pipeline. The ami-name is constant at this point, while the installed packages version is different for each build

Improve the unicity of the bake key also taking into account multiple accounts

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/config/JedisConfig.groovy

Needed to add a timeout value since the JedisPool constructor requires one if you want to include a password.  This change supports using the Azure hosted Redis service.

Add support for password on a redis connection

---

rosco-web/config/packer/install_packages.sh

Remove configuration files from either debian and yum repos after installing packages. We are doing this because we put basic auth credentials in repo urls.

Remove config files with possible credentials from baked AMIs

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverter.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverterSpec.groovy
rosco-web/config/packer/aws-chroot.json
rosco-web/config/packer/aws-ebs.json

Part of a series of PR adding build info support for travis integration on AWS
by adding new build_info_url tag to the images in order to be able to full fill the build info correctly for travis.
This PR adds a build_info_url BakeRequest to Rosco
Rosco will add the build_infor_url as a ec2 tag.
This is the final result
Related PRs:
https://github.com/spinnaker/orca/pull/856
https://github.com/spinnaker/clouddriver/pull/652
https://github.com/spinnaker/deck/pull/2304

Travis support for rosco

---

rosco-web/config/packer/install_packages.sh

Have change the provision_deb functions so it loops over $repository split on ;
This makes it possible to set more the one deb repo in debianRepository and have them all added. I did split the settings string on ; with to my knowledge is a non valid character for the urls and there by safe as a character to split on.
Please add comments.

Changed provision_deb so it can take multiple repos

---

rosco-web/etc/init/rosco.conf

When I merged the job-runner logic from rush into rosco, I neglected to add the config to set HOME env when running rosco from an installed .deb package.
This omission left the aws builder for packer unable to resolve .aws/credentials: https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L125

Set HOME env when running from deb package.

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy

The 'START_DOCKER_SERVICE_BASE_COMMAND' breaks for us when running docker bakes, so locally I removed it rather than trying to find a way to have it work, as I felt that it didn't belong under the responsibility of Rosco to ensure that the docker service was running. And as @duftler pointed out on the slack channel yesterday:
That is almost certainly a vestige of rush's prior incarnation of running bake jobs as containers themselves.

Removing the handling of the docker service from the DockerBakeHandler

---

rosco-web/rosco-web.gradle

This change will fix problems where logrotate ignores
/etc/logrotate.d/rosco due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)

Update logrotate file permissions

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-web/config/packer/aws-chroot.json
rosco-web/config/packer/aws-ebs.json

The packer part is quite ugly since it's not possible to pass a list on the command line as `var`.
Accounts and regions must me passed one by one

Support the share_with and copy_to parameters as extended_attributes.

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy

Well, technically, don't check the instance type as it is defined by
region in the config. This approach is more inline with how AWS bakery
requests work.

Remove instance type from openstack bakery request.

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactory.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy

The thought here is to let ``` organization ``` become a full member of the bakeRequest, and let it, ``` ami_name ``` and ``` ami_suffix ``` provide the default basis for the ``` docker_target_image ```. 
We discussed (@duftler) letting the docker specific parameters like the docker image name come into the BakeRequest, but in retrospect it seems to me that re-using the ami_name/ami_suffix names, (and rather refactoring those some time in the future) would make more sense and keep the ``` BakeRequest ``` as uncluttered as possible. And I'm suggesting that organization might be general enough to be usefull for other providers, but this might be wrong? I think both ways work, so feel free to mix it up.  This PR will ofc also require a PR in Orca before the ``` organization ```  field can be …

Adding docker specific naming conventions

---

Dockerfile

Noticed that packer is running from rosco instead of rush now. I wasn't able to bake ami successfully while  running rosco docker image.  Thus cloning similar change from rush docker to rosco docker. 
(https://github.com/spinnaker/rush/commit/f94712ad5fb2c4ae729c4ab8cc3a620f0903054a#diff-3254677a7917c6c01f55212f86c57fbf)

Install packer in docker for rosco (cloned from rush)

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/JobExecutor.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy

BakeryController.runBake starts the job, sleeps for a second and then updates the job
JobExecutor.startJob uses threadpool to run the jobs
If there are multiple bakes from a single jenkins build, some of them fail with NPE because of the timing issue
To fix it, instead of sleeping for 1s, check for job status every 1/2 second for 5 seconds

Fix for NPE in BakeryController.runBake due to timing issue

---

rosco-web/config/rosco.yml
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/AllStatusEndpoint.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/InstanceStatusEndpoint.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/StatusHandler.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/mvc/AllStatusMvcEndpoint.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/endpoints/mvc/InstanceStatusMvcEndpoint.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/endpoints/AllStatusEndpointSpec.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/endpoints/InstanceStatusEndpointSpec.groovy

Adding two instance status endpoints in order to check running bakes.
Both are enabled by default
To disable they add to rosco-local.yml
endpoint.status.enable : true
To enable sensitive flag add to rosco-local.yml
endpoint.status.sensitive : false
**/status/all**
```
{  
"instance":"a74e6995-ab43-40e2-9b40-cc6afe01e048",
"instances":{  
"a74e6995-ab43-40e2-9b40-cc6afe01e048":{  
"status":"RUNNING",
"bakes":[  
{  
"id":"a459c99e-3ee1-41a0-a45d-de48b0fb2e70",
"state":"RUNNING",
"result":null,
"resource_id":"a459c99e-3ee1-41a0-a45d-de48b0fb2e70"
}
]
},
"4e51032e-a114-11e6-80f5-76304dec7eb7":{  
"status":"RUNNING",
"bakes":[  
{  
"id":"6442a7c8-a114-11e6-80f5-76304dec7eb7",
"state":"RUNNING",
"result":null,
"resource_id":"6442a7c8-a114-11e6-80f5-76304dec7eb7"
}
]
}
}
}
``` …

Add instance status endpoint

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/config/RoscoAzureConfiguration.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy
rosco-web/config/rosco.yml

Also bump the timeout for rosco since Azure packer consistently exceeds the 10 minute default timeout.

fix name of Azure packer-specific storage account config property. 

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy
rosco-web/config/packer/docker.json

This will let docker images replicate the behavior used with AMIs so that we can have the appversion and build url attached to the docker image.

Adding build and package metadata to baked docker image

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactory.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactorySpec.groovy

I had misunderstood the use of ami_suffix. And it seems unnatural to add it to the docker image name. For docker images I'm thinking that multiple tags / labels would be a better approach if we need such a qualifier.

Removing ami_suffix from docker image name

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy

In our rosco setup, we bake with some templates that require root and others that do not require root.
Originally, I thought that I would simply be able to define `templatesNeedingRoot: my-template-name.json` and then anytime I bake with that template it would be run with root. This was not the case since only the bakery default templateFile was considered when determining whether `sudo` should be used.
I modified things slightly so that `getBaseCommand` considers the passed in `template_file_name` if it exists. If it does not exist the behaviour remains the same.

Pass templateName to getBaseCommand to determine whether sudo is required

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/executor/BakePoller.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/executor/BakePollerSpec.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy

Renamed the spectator meter names because one was ambiguous and the other non-standard
bakesCompleted [Timer] formerly "bakes"   (was ambiguous)
bakesRequested [Counter] formerly "bakes" (was ambiguous)
- changed the tag structure as well
bakesActive    [Gauge]   formerly "bakes.local"  (removed '.' from name and clarified)
@duftler

Fix instrumentation

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactory.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy

This PR tries to let us use and control organization, tag and the image name for docker in a more coherent way while still respecting the current contract. My main motivation is to be able to enrich the bake step in deck for a separate PR.

Adding docker tag, organization and name handling

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeOptions.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/config/RoscoAWSConfiguration.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/config/RoscoAzureConfiguration.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactory.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/ImageNameFactory.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactory.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverter.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerImageNameFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/ImageNameFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverterSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy
rosco-web/config/packer/aws-windows-2012-r2.json
rosco-web/config/packer/azure-windows-2012-r2.json
rosco-web/config/packer/scripts/aws-windows-2012-configure-ec2service.ps1
rosco-web/config/packer/scripts/aws-windows.userdata
rosco-web/config/packer/scripts/windows-configure-chocolatey.ps1
rosco-web/config/packer/scripts/windows-install-packages.ps1
rosco-web/config/rosco.yml

There are 2 PR's that need to be merged before this PR can be merged. 
- Spinnaker: [PR #1390](https://github.com/spinnaker/spinnaker/pull/1390)
- Orca: [PR #1146](https://github.com/spinnaker/orca/pull/1146)
I've also raised an issue with Packer as when using the powershell provisioner via Spinnaker, the powershell command line isn't properly formed. Issuing the exact same packer command line via the command line works as expected. Please note that this only impacts Azure. AWS is working as expected.
- Packer issue: [Issue #4478](https://github.com/mitchellh/packer/issues/4478)

(AWS/Azure) Add support for Windows using Chocolatey as package manager.

---

rosco-web/config/packer/install_packages.sh

Testing of this change was done in AWS and Azure environments targeting a CentOS 7.1 image. There are 2 ways to specify your target RPM repositories: setting the value of 'yumRepository' in your rosco-local.yml file or via an extended attribute in your bake state. For testing purposes, we used the extended attribute in our bake stage to override the configured value for the 'yumRepository' setting.
To replicate, add an extended attribute named 'repository' in the Bake Configuration of a bake stage. Set the value of this extended attribute to a semi-colon separated string (ie 'http://jfrog-artifactory.repo/artifactory/dotnet-core/;http://nginx.org/packages/centos/7/$basearch/'). In the 'Packages' field in the Bake Configuration, add a package from each repository (ie 'dotnet-core-runtime …

Allow for multiple RPM repositories

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverter.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageUtil.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/DebPackageUtil.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/NupkgPackageUtil.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/RpmPackageUtil.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverterSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/DebPackageUtilSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/NupkgPackageUtilSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/RpmPackageUtilSpec.groovy

This should make it easier to add more implementations in the future.
No new features, only refactoring.
* Made a new PackageUtil interface and moved code into three different implementations (for rpm, nupkg and deb)
* Updated tests to reflect the new implementation

Refactor package and version handling

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/config/RoscoGoogleConfiguration.groovy

This makes the google config more similar to that of the other providers.
The config in rosco-web was left untouched, since it would override existing configurations of rosco with this change in place.

Deprecate google.gce.bakeryDefaults in favor of google.bakeryDefaults

---

rosco-web/pkg_scripts/postInstall.sh

Apparently `set -e` was called somewhere in the install scripts, so if `packer` isn't installed, `packer --version` fails, causing the install script to exit. Wrapping this in a function will let me inspect the return code and decide what to do safely.

fix(install): Wrap packer failure in function.

---

rosco-web/pkg_scripts/postInstall.sh

The install script runs as `sh`, not `bash`.

fix(install): Made postInst sh-compatible, not bash.

---

rosco-web/pkg_scripts/postInstall.sh

This will be useful if the build system already pulls in packer but do not have path configured.
Also there is a bug in the post install script. It does apt-get install within apt-get install, so it will not succeed for those who are using deb package. Ideally unzip should be a dependency. Nonetheless this fix is necessary.

To find packer version, use full path for packer. 

---

Dockerfile.slim

I tested this locally on a Docker container and verified that
the config directory structure looks how we actually want it to this
time. @duftler FYI.  Sorry for the repeated attempts to solve this.

fix(Dockerfile): Navigate Docker's wonky COPY command.

---

rosco-web/config/packer/scripts/windows-configure-chocolatey.ps1
rosco-web/config/packer/scripts/windows-install-packages.ps1

Updated Powershell script that is responsible for installing Chocolatey packages when baking Windows images to properly parse package names. The logic is now the same logic that is used in Rosco when parsing package names.
Package names like 'nodejs.install.7.9.0' are now split into name ('nodejs.install') and version ('7.9.0') and the version is now included when installing the package via Chocolatey command line.

fix(Rosco/Chocolatey) Properly install Chocolatey (NUPKG) packages that include the package version (#1616)

---

halconfig/images.yml
halconfig/packer

This adds a symlink to the packer template directory, as well as adds a list of default images for each provider. These'll be used during config validation & generation by halyard.

chore(halyard): Add links to templates & images

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/Artifact.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/executor/BakePoller.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/BakeRecipe.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/BakeStore.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/RedisBackedBakeStore.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/executor/BakePollerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy

The motivation here is to enable Artifact decoration for bakes without altering current workflow. I've tried to write this in such a way that it's easy to make the bakeprovider more generic in the future. This also means I had to take some choices so feel free to weigh in. This change gives us the following output on the bake endpoint:
```
curl -s http://localhost:8087/api/v1/global/bake/e2f492f2-ee4e-4bc3-b2b8-f0e8179625c7 | jq .
{
"id": "e2f492f2-ee4e-4bc3-b2b8-f0e8179625c7",
"ami": null,
"image_name": "myrepo/the-team/ah4234h",
"artifact": {
"name": "the-team/mycontainer",
"type": "docker",
"version": "1494232370153",
"reference": "containers.schibsted.io/delivery-team/delivery-dash:ah4234h",
"metadata": {
"build_info_url": "https://travis-ci.org/mybuild/53",
"build_number": "53"
}
}
} …
```

feat(artifact/decoration): Artifact decoration spinnaker/spinnaker#1348

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy

This matches the behavior of Orca, in which each instance is reported using `random-string@hostname`

feat(core): Add hostname to roscoInstanceId

---

halconfig/images.yml
rosco-web/config/rosco.yml

@duftler because the images between `google.gce.bakeryDefaults.baseImages` and `google.bakeryDefaults.baseImages` are appended to one another, this shouldn't cause any images to be deleted -- unless -- if people have switched to the non-deprecated config (`google.bakeryDefaults.*`), and are depending on one of the three images listed in  `google.gce.bakeryDefaults.baseImages`, they will be overwritten because of how spring merges profiles. I'll check with our bigger users to see if this will affect them.

chore(config): Switch to non-deprecated config & remove 12.04 from gce images

---

rosco-web/config/rosco.yml

Update the default Rosco configuration to support Ubuntu 14.04 in us-east-2 on AWS.

config(ami): Add Ubuntu 14.04 ami for us-east-2

---

rosco-web/config/packer/install_packages.sh

This change resolves an issue where yum was not able to locate some packages if an image is being created from a previously baked image and both are using custom repositories. When a base image is created that included a repository, that repository was being named "spinnaker-0". As part of the base image generation, if "upgrade=true" is set, the yum cache will be updated and include the "spinnaker-0" repo in it's cache. When another image is created using that base image and includes it's own repository, the repository was also being named "spinnaker-0". This conflicts with the yum cache and if the 'repomd.xml' file that yum retrieves from the repo is older than the 'repomd.xml' that was cached when creating the base image, yum will ignore the file. This will potentially cause yum not to …

fix(bake/package/rpm): Added timestamp to yum repo name and file name

---

build.gradle
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy

Add an explicit import on @ErrorConfiguration to enable the
consistent exception handling that exists across other
Spinnaker services.

chore(dependencies): Bump spinnaker-dependencies version

---

Dockerfile
Dockerfile.slim
rosco-web/pkg_scripts/postInstall.sh

I'm using the custom templates of packer to bakery my AMIs, and using the packer version installed with rosco, I receive the error below
Using the latest version of packer, it's works.
Could we bumping it?
I know that in the spinnaker/spinnker there is an script that install the packer too, so I going to update there if necessary.
<details>
==> amazon-chroot: AMI: ami-XXX
==> amazon-chroot: Waiting for AMI to become ready...
==> amazon-chroot: Deleting the created EBS volume...
Build 'amazon-chroot' errored: unexpected EOF
==> Some builds didn't complete successfully and had errors:
--> amazon-chroot: unexpected EOF
==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not map[string][]string
2017/10/18 18:16:42 packer: 
2017/10/18 18:16:42 …

chore(packer): Bump packer version

---

rosco-web/config/packer/aws-ebs.json

This reverts commit 8f0564784f6a04631b7531c95cd876a93e4503d2.
Per this Packer issue `pause_before` isn't being expanded: https://github.com/hashicorp/packer/issues/5115

fix(rosco): Revert Make pause_before configurable (#224)

---

rosco-web/config/rosco.yml

We're updating the trusty base image ami id's to a newer version.

updated ami ids for baseImage

---

halconfig/images.yml
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/config/RoscoAWSConfiguration.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-web/config/packer/aws-ebs.json
rosco-web/config/packer/aws-multi-ebs.json
rosco-web/config/packer/aws-windows-2012-r2.json
rosco-web/config/rosco.yml

Packer defaults to using on-demand pricing when creating AWS AMI's. Given that most bakes take considerably less than an hour, using on-demand pricing is wasteful since you pay for the full hour. This PR enables Packer to use spot pricing and defaults to 'auto' which allows Packer to automatically discover the best spot price. Setting 'spotPrice' to '0' (zero) causes Packer to use on-demand pricing.

feat(bake) Added AWS spot pricing configuration when baking AMI's. Defaults to 'auto'.

---

rosco-web/etc/init/rosco.conf

Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.

fix(rosco/log): Append to log instead of overwrite

---

halconfig/images.yml
rosco-web/config/packer/aws-ebs.json
rosco-web/config/packer/aws-multi-ebs.json
rosco-web/config/packer/aws-windows-2012-r2.json
rosco-web/config/rosco.yml

A change was made to rosco recently to add the ability to use spot instances when baking. In the process it also changed spot to be the default. The functionality itself is fantastic, but defaulting to spot actually comes along with a few additional requirements. That causes bakes to start failing on update. So defaulting to the same bake style as we had in 0.102.0 and before, but leaving all the options there so users can turn spot on.
- Change the spotPrice default in the virtualizationSettings to 0 instead of auto. Set to auto it was defaulting to doing bakes using spot, which is a big change from the way we have been operating.
- Need to quote the spot price in the templates, otherwise packer throws an error with "expected type 'string', got unconvertible type 'float64'"
- Leave the …

feat(bake) The addition of spot changed the defaults, swap them back

---

README.md
build.gradle

Starting rosco with ./gradlew -DDEBUG=true now causes the JVM to
listen for a remote debugger on port 8187.
them.

chore(build): add debug flag to rosco build

---

rosco-web/config/packer/aws-windows-2012-r2.json

The current aws-windows-2012-r2.json Packer script is malformed, causing
all bakes of AWS Windows AMIs to fail if they are using the default bake
script.  https://github.com/spinnaker/spinnaker/issues/2598

fix(bake): Fix broken AWS Windows bake script

---

build.gradle
rosco-core/rosco-core.gradle
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/JobRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ClouddriverService.java
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ServiceConfig.java
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactorySpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy
rosco-manifests/rosco-manifests.gradle
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestService.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-web/rosco-web.gradle
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/V2BakeryController.java
settings.gradle

Still missing:
1. Downloading helm values files
2. Setting helm --set values
3. Deleting staged helm charts
4. Creating non base64 artifacts
5. Polling of running bake tasks -- the bake is currently synchronous

feat(bake/manifests): Rudimentary bake manifest support

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy

When baking a GCE image, set the reference of the produced artifact to the URI for the produced image

feat(artifacts): Update GCE bake to send image reference

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/JobExecutor.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/config/LocalJobConfig.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy

Given that the v2 deployer doesn't wait for rosco to drain all work before shutting down, this gives Kubernetes a chance (with `terminationGracePeriodSeconds`) to allow rosco to finish any ongoing bakes.

feat(core): add shutdown hook to avoid killing running jobs

---

Dockerfile
Dockerfile.slim

Upgrades packer binary to 1.2.2 in both Docker and Docker.slim.
This PR addresses this issue here:
https://github.com/spinnaker/spinnaker/issues/2545

chore(packer) - upgrade packer binary to 1.2.2

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/executor/BakePoller.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackerArtifactService.java
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy
rosco-web/config/packer/gce.json
rosco-web/config/packer/install_packages.sh

Updates the rosco bake endpoint to accept a list of artifacts and passes these artifacts to packer.  Packer does not yet consume these artifacts, which will be implemented in a later pull request.

feat(bake/artifacts): Pass artifacts to packer

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java

The `--set` command added multiple times does not get honored in the `org.apache.commons.exec.CommandLine` when getting executed. Instead we can use `--set-string` to concat all of the values together like `--values`

fix(kubernetes): --set multitple times does not work with exe

---

rosco-web/pkg_scripts/postInstall.sh

Upgrades packer binary to 1.2.2 in `rosco-web/pkg_scripts/postInstall.sh`.
I found Docker's packer was already upgraded, but not `postInstall.sh`.
refs https://github.com/spinnaker/rosco/pull/244
This PR addresses this issue here:
https://github.com/spinnaker/spinnaker/issues/2545

chore(packer) : upgrade packer binary to 1.2.2

---

rosco-web/config/packer/scripts/windows-install-packages.ps1

Currently, when installing multiple packages, all are installs are attempted and only the final exit code is used (it falls through to Packer scripts in $LastExitCode).  Instead, exit with the same exit code as soon as the first package install fails.

fix(bake/chocolatey): Observe Chocolatey exit codes

---

rosco-web/config/packer/aws-windows-2012-r2.json
rosco-web/config/packer/azure-windows-2012-r2.json

The current Chocolatey scripts always use the latest version, meaning
that bugs in new releases of Chocolatey may affect Windows bakes. This
pull allows a "chocolateyVersion" attribute to be applied to a bake step
to manually control the version installed by the scripts.
Default behavior is unchanged, it will install the latest version.

feat(bake/windows): Allow Chocolatey version control via attributes

---

Dockerfile
Dockerfile.slim
rosco-web/pkg_scripts/postInstall.sh

Upgrades packer binary to 1.3.1 in Dockerfiles and `rosco-web/pkg_scripts/postInstall.sh`.
This PR addresses the issue here: https://github.com/spinnaker/spinnaker/issues/3505

chore(packer): upgrade packer binary to 1.3.1

---

rosco-web/config/packer/oci.json

packer variable oracle_pass_phrase should be optional, not required.

fix(bakery/oracle): private key passphrase is optional

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy

Packer 1.3 now enforces that aws_spot_price_auto_product can only be passed if aws_spot_price is set to "auto". The default settings that ship with Spinnaker set aws_spot_price to "0" and aws_spot_price_auto_product non-null. Gate passing through the product value so that it is only passed through if the spot price is "auto".

fix(packer): Fix spot pricing flags

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy

@duftler 
We upgraded to Packer 1.3+ (1.3.3, specifically) and the line with the AMI name changed.  This accounts for that change.  Not entirely thrilled about this, but it works and follows the current pattern.
Merge it if you like, or leave it here just for posterity - either way we're using it in our own deploy.  I think ultimately resolving this issue the way @duftler outlined in the TODO comment is the way to go.

fix(packer): Determine image name from unencrypted AMI log line

---

rosco-web/config/packer/azure-linux.json

Per shared knowledge from Azure Compute team, using VM size "DS2 v2" could greatly improve the performance of Azure VM provision and de-provision by using packer in the bake stage. We've tested it in our local dev Spinnaker environment and it was true.
Need to mention that the $ cost of the new size is a little bit more expensive than the original one. But making this change is definitely not for charging more money but out of the consideration of improving performance. In addition, the charge diff between this two sizes is about 0.05 USD/hour for [Linux ](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/) and 0.1 USD/hour for [Windows](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/windows/), while given the bake-image action could be finished …

config(provider/azure): update the image base vm size in packer

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeStatus.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/JobRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocalSpec.groovy
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java

This is a fix for https://github.com/spinnaker/spinnaker/issues/3063.
Previously, #269 attempted to fix this issue by capturing stdout and stderr separately, however this change caused a regression and was reverted in #279.
This fix takes a similar approach to #269 but avoids the regression by keeping stdout and stderr completely separate and not attempting to merge the streams.  Additionally, the change is only enabled when baking Helm manifests, so other bake functionality will not be impacted.
One limitation of this change is that non-fatal warnings printed to stderr will be ignored if the `helm template` command exits with error code 0.  (Previously, non-fatal warnings would also not be reported, but would be merged into the output artifact data.  Consequently, the bake stage would …

fix(bake/manifests): capture only stdout in Helm bakery - 2nd attempt

---

rosco-core/rosco-core.gradle
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/RedisBackedBakeStore.groovy

Replace `jedis.keys` invocations with a kork `withKeyScan` invocation, like https://github.com/spinnaker/igor/pull/270 (instead of implementing a scan loop directly). Came up from Redis slowlog entries reaching dozens of ms. 
Note that I did not change out the other `jedisPool` usages in `RedisBackedBakeStore.groovy`. Replacing them introduced a bunch of these 'ambiguous call' warns:
I was also unable to locate a `jedis.time()` signature for `getTimeInMilliseconds()`. The 'TIME' command is seemingly only exposed directly on BinaryClient.
For these reasons I only touched the 'keys' invocations in this initial commit.

perf(redis): Stop using KEYS command in BakeStore

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java

Fixes spinnaker/spinnaker#4387
If an artifact is empty, we throw an NPE when downloading it rather than just pass an empty artifact along to the caller.
In general it's not overly useful to have an empty artifact, but in some cases (ex: a values.yaml file for a Helm bake) it's reasonable to have no content.

fix(artifacts): Fix NPE on empty artifact

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java

Fixes spinnaker/spinnaker#4110
When supplying an artifact without a reference, we currently throw an NPE that is hard to debug. Replace this with a better error message.
(At some point we could consider if we even need a reference at all, or if we could fall back to something else, but for now this will at least make the restriction clearer.)

fix(bake): Improve error message

---

rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy

A few of the rosco tests fail when we upgrade groovy because groovy no longer considers objects equal they are identical except that a field is null in one vs empty array in the other.
That was masking the fact that we weren't stubbing out the getMaskedPackerParameters function on our mock CloudProviderBakeHandler. Add in that stubbing, and also change the calling code to use the actual accessor rather than the groovy-generated synthetic one.
There's probably a way to factor out some of the common logic in the tests so changes like this don't need to touch as many lines, but for now just making the required change in each test.

test(core): Fix tests that break with groovy upgrade

---

README.md
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/alicloud/AliCloudBakeHandler.java
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/alicloud/config/RoscoAliCloudConfiguration.java
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/alicloud/AliCloudBakeHandlerSpec.groovy
rosco-web/config/packer/alicloud-multi.json
rosco-web/config/packer/alicloud.json
rosco-web/config/rosco.yml
rosco-web/rosco-web.gradle
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy

This is a new provider used to build VM images on the [Alibaba Cloud](https://www.alibabacloud.com/). This PR add two template `alicloud.json` and `alicloud-multi.json` to build VM image in single and multiple regions.

feat(provider/alicloud): Add Alibaba Cloud bakery to build VM image

---

Dockerfile
Dockerfile.slim
rosco-web/pkg_scripts/postInstall.sh

Upgrades packer binary to 1.3.2 so we can take advantage of multi-region and HA bakes through the use of subnet_filter and vpc_filter.
https://github.com/spinnaker/spinnaker/issues/4114

chore(packer): upgrade packer binary to 1.3.2

---

Dockerfile
Dockerfile.slim
rosco-web/pkg_scripts/postInstall.sh

Turns out packer 1.3.2-1.3.4 have a lot of crash issues and builders filtering do not work.
spinnaker/spinnaker#4114

chore(packer): upgrade packer binary to 1.3.5

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java

using `--set` instead of `--set-string` ensures that values of different types get injected into into the chart properly. the most common use case for this is values that are used as `bool` in templates. Previously, these values would cause errors because they weren't properly converted.

fix(bake/helm): use --set instead of --set-string

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/test/groovy/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsSpec.groovy

When baking Helm charts using the command `helm template`, ignore the templates in the tests in the directory `<CHART>/templates/tests`.
Resolves [issue](https://github.com/spinnaker/spinnaker/issues/4831)

fix(bake/helm): Remove tests directory when baking Helm chart

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java

reverts a change introduced in #418 where we went from using
`--set-string` to `--set`. This change caused backwards incompaitble
changes because the parser for `--set` in helm coerces integers into
floats when it injects them into templates. `--set-string` was
introduced to fix this in helm 2.

fix(bakeManifest): revert to set-string

---

rosco-manifests/rosco-manifests.gradle
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/test/groovy/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java

Fixes spinnaker/spinnaker#4874.
We currently throw an exception if a helm artifact doesn't have a reference. We're only using that reference to generate a file name to use when downloading the artifact; helm artifacts don't actually need a reference.
Fix this by just falling back to the name-version if there is no reference defined.
(I'd like to refactor this code a bit, and just use a UUID as the file name to avoid all this, but this felt like a smaller change and I'd like to cherry pick the fix.)

fix(helm): Fix baking of helm artifacts

---

rosco-manifests/rosco-manifests.gradle
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/test/groovy/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java

Manual cherry pick of #442; the only conflict was the imports at the top of `HelmTemplateUtils.java`.
We currently throw an exception if a helm artifact doesn't have a reference. We're only using that reference to generate a file name to use when downloading the artifact; helm artifacts don't actually
need a reference.
Fix this by just falling back to the name-version if there is no reference defined.

fix(helm): Fix baking of helm artifacts (#442)

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestRequest.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java

adds an option to toggle between `--set` and `--set-string`. we recently
had to revert a commit which changed `--set-string` to `--set` and
introduced a breaking change. this keeps the default behavior of
`--set-string` but allows users to choose which option they want to use.

fix(bakeManifest): helm --set option

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeTemplateUtils.java

if it's not set, it'll fetch from `master`, which is unintended.

fix(kustomize): fetch new artifacts using the same version

---

Dockerfile.slim

Fixes regression introduced in [this PR](https://github.com/spinnaker/rosco/pull/450) that broke the build.

fix(dockerfile): correct hashicorp packer path to 1.4.4

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeOptions.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy
rosco-web/config/rosco.yml

* feat(packer): set custom repository per base image
Right now there is the posibility to add one repository per package type (deb/rpm)
this collides when trying to setup multiple flavours/versions repositories for the
same package type.
e.g. When baking with Ubuntu you can only setup one repository index (xenial, bionic)
this forces you to put in the same repository index all packages no matter which
version are they intented to be.
With this patch, you can add a customRepository property per BaseImage with overwrites the
debianRepository/yumRepository/chocolateyRepository global config entries, this provides
more granularity on the repository configuration.
https://github.com/spinnaker/spinnaker/issues/4894

feat(packer): set custom repository per base image

---

gradle.properties
rosco-manifests/rosco-manifests.gradle
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloader.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeBakeManifestRequest.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeTemplateUtils.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImplTest.java

This adds support for `git/repo` as an artifact type for a kustomize bake. This is a work in progress involving changes to other services as well, so we're leaving in the old logic (baking from a github/file artifact) until the rest of the PRs are merged. 
@ezimanyi PTAL?

feat(kustomize): support git/repo artifact in kustomize bake manifest

---

rosco-web/config/rosco.yml

It appears the `ubuntu-1404-lts` image family was unpublished, causing our builds to break.  This will need to be cherry picked into 1.17, too.

fix(gce): Remove recently unpublished 'trusty' base image, add 'bionic'

---

halconfig/images.yml

Need to make the same change as https://github.com/spinnaker/rosco/pull/471 except in `halyard/` in order for releases to pick them up.

fix(gce): Hardcode Trusty GCE image in halconfig/images.yml

---

halconfig/images.yml

Need to apply https://github.com/spinnaker/rosco/pull/470 to `halyard/images.yml` to have it work with releases.

fix(gce): Remove Trusty GCE image in halconfig/images.yml, add Bionic

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/executor/BakePollerSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy

The all-arg and no-arg constructors for Artifact were deprecated in spinnaker/kork#429. Replace their usages with a builder.

refactor(artifacts): Use builder to create artifacts

---

Dockerfile.slim

The Alpine builds haven't been updated in months. See
spinnaker/spinnaker#5204.

chore(release): Use buster-slim instead of alpine as the base OS

---

gradle.properties
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/config/RedisConnectionInfo.groovy

Revert "chore(dependencies): Upgrade Spring Boot to 2.2.1 (#468)"
This reverts commit c2b3a74d

chore(dependencies): Reverting Spring Boot 2.2 upgrade

---

Dockerfile.java8
Dockerfile.slim
Dockerfile.ubuntu
Dockerfile.ubuntu-java8

Install Helm 3 Binary alongside Helm 2.
Part of https://github.com/spinnaker/spinnaker/issues/5474
```
$ docker build -t compile -f Dockerfile.compile .
$ docker build -t slim -f Dockerfile.slim .
$ docker run --rm slim helm version
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
$ docker run --rm slim helm3 version
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

chore(build): Install Helm3 Binary to Rosco Container Image

---

Dockerfile.java8
Dockerfile.slim
Dockerfile.ubuntu
Dockerfile.ubuntu-java8
rosco-web/pkg_scripts/postInstall.sh

Requesting a backport of this packer patch which should fix a problem with our bakery hanging intermittently when running in parallel & using WinRM.

fix(rosco): Update Hashicorp Packer version in rosco to 1.4.5 (bp #555)

---

halconfig/README.md
halconfig/rosco.yml
rosco-web/config/rosco.yml

As with the other microservices, let's push defaults that were being set by Halyard down to the core so that the defaults are the same for everyone.
Halyard was setting the redis connection based on the services.redis value; push that down to the base. Users who were manually setting this before will not be affected as they will override this value; users who did not set this at all before will still fall back to the localhost:6379 which is the fallback at the point we read it.
Halyard was also setting the configDir to /opt/packer/config. The default in the base config was placeholder /some/path/to/config/packer; replace this with what Halyard was setting. I suppose that if someone was actually putting their templates in /some/path/to/config/packer then this would break them until they …

config(core): Push Halyard default configs down to core

---

gradle.properties
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeTemplateUtils.java
rosco-manifests/src/test/groovy/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsSpec.groovy

An upcoming kork bump is making artifact null-safe by setting fields to empty string. Fix the couple of places that expected null.

fix(tests): Fix tests failing on artifact

---

rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy

I'm now reverting the change to make artifacts translate null to empty which will break this test I just udpated; let's just make the tests agnostic to whether the artifact returns null/empty.

fix(test): Make test agnostic to null/empty string

---

rosco-web/pkg_scripts/postInstall.sh

This is the equivalent to #536 but for the deb/rpm packages.

chore(build): Add Helm3 binary install to Rosco packages

---

rosco-web/rosco-web.gradle

kork-runtime brings in kork-swagger for the runtime component configuration

fix(dependencies): depend on only swagger-annotations for compile

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/executor/BakePoller.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/executor/BakePollerSpec.groovy

Fixes spinnaker/spinnaker#5998.
* test(bake): Add test exercising bake artifact handling
There is currently no test that exercises the logic that updates the name and uuid on artifacts produced by a bake.  Add a test exercising this logic that currently fails and will be fixed in the next commit.
* fix(bake): Fix error when updating artifacts after bake
When artifacts were made immutable, this usage was missed as it did not have tests (and was in groovy so compilation didn't catch it). Instead of mutating the artifacts, return copies with the appropriate fields changed.

fix(bake): Fix error when updating artifacts after bake

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java

* don't hide the root cause of artifact download failure to ease up troubleshooting

refactor(artifact downloader): Chain root cause when rethrowing exception

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java

to clean up warnings like
```
---> HTTP PUT http://spin-clouddriver-ro.spinnaker-stage:7002/artifacts/fetch/
2020-11-20 22:03:03.649  WARN 1 --- [0.0-8087-exec-1] c.n.s.okhttp.OkHttp3MetricsInterceptor   : Request PUT:http://spin-clouddriver-ro.spinnaker:7002/artifacts/fetch/ is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:98)
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:36)
at com.netflix.spinnaker.rosco.manifests.ArtifactDownloaderImpl.lambda$downloadArtifact$0(ArtifactDownloaderImpl.java:29)
at com.netflix.spinnaker.kork.core.RetrySupport.retry(RetrySupport.java:34)
at …
```

chore(logs): allow anonymous clouddriver artifact fetching

---

rosco-core/rosco-core.gradle
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ServiceConfig.java

by using the SpinnakerRetrofitErrorHandler class from kork, exceptions when rosco calls
other spinnaker microservices are more visible to the user
So, instead of seeing, for example
500
deck now shows
Status: 500, URL: http://spin-clouddriver-ro.spinnaker:7002/artifacts/fetch/, Message: Artifact credentials 'helm-account' cannot handle artifacts of type 'git/repo'
Visually, before:
after:
related to https://github.com/spinnaker/spinnaker/issues/5473

feat(exceptions): improve error handling

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy

This PR is for resolving   https://github.com/spinnaker/spinnaker/issues/5448.
When using Azure provider if we have a custom packer template which creates shared gallery image , the "Image" output variable still reference the managed image which also gets created as a part of the shared image gallery version. It is possible to create shared image gallery images by adding extension attributes in bake stage json as it is passed on to the packer template as variables. However the rosco azure bake handler only scraps Managed image id which is also created in the due process. But if one were to create shared gallery image, then the idea is that we don't need managed image id reference anymore. So the output could reference the shared image gallery id and this could be in turn used for deploy. …

feat(bakery/Azure): Changes to extract shared-image-gallery image name from logs

---

Dockerfile.slim
Dockerfile.ubuntu

Helm V2 is EOL and install scripts are broken, see https://github.com/helm/helm/pull/9623 
I'm hardcoding the version to the latest helm v2 release.

chore(build): hardcode helm v2 version to final release

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/Bake.groovy

This allows the Bake class to include the base AMI for use with managed delivery, related to https://github.com/spinnaker/orca/pull/4071.

chore(bake): add base ami to completed bake details

---

rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/TestDefaults.groovy

Refer spinnaker/spinnaker#6537
During verification of spring boot upgrade using spinnaker/kork#895, received below error:
```
Task :rosco-core:compileTestGroovy
startup failed:
/rosco/rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy: 69: Only @Shared and static fields may be accessed from here @ line 69, column 7.
SOME_BAKE_REQUEST | SOME_BAKE_RECIPE | SOME_BAKE_RECIPE_NAME | null                 | SOME_AMI_ID       | SOME_BUILD_INFO_URL | SOME_BUILD_NR
^
/rosco/rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandlerSpec.groovy: 68: Only @Shared and static fields may be accessed from here @ line 68, column 27.
null              | SOME_BAKE_RECIPE | SOME_BAKE_RECIPE_NAME | null                 | …
```

chore(dependencies): Upgrade Spring Boot to 2.2.13

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImplTest.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java

These changes should really have been in https://github.com/spinnaker/rosco/pull/750.  That PR added detail from clouddriver, but at the expense of detail from rosco about the artifact and messages about helm charts and downloading.  This restores the info from before that PR.
where before this PR that was:

Improve clouddriver exception handling

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy

There was a TODO to support multiple accounts, this PR implements it. Based on the GCE provider method.
If no accounts found, it returns a readable exception.

feat(provider/azure): Adding support for multiple managed accounts

---

.github/workflows/release.yml
rosco-web/rosco-web.gradle

Incorporates the new io.spinnaker.artifactregistry-publish plugin to rosco-web. This will publish the apt and rpm packages for rosco to the Google Artifact Registry

feat(publishing): artifact registry publishing

---

.github/workflows/release.yml
rosco-web/rosco-web.gradle

- there's no need to apply io.spinnaker.artifactregistry-publish in rosco-web.gradle.  The
[spinnaker project plugin does that for us](https://github.com/spinnaker/spinnaker-gradle-project/blob/49d277f619d9a79c75be91c358ea38658c84de7f/spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/project/SpinnakerProjectPlugin.groovy#L34).
- apt publishing is enabled by default, so no need to specify `ORG_GRADLE_PROJECT_artifactRegistryPublishAptEnabled: true` in release.yml
- the logic in [ArtifactRegistryPublishPlugin](https://github.com/spinnaker/spinnaker-gradle-project/blob/49d277f619d9a79c75be91c358ea38658c84de7f/spinnaker-project-plugin/src/main/groovy/com/netflix/spinnaker/gradle/publishing/artifactregistry/ArtifactRegistryPublishPlugin.groovy#L50) publishes debian packages …

chore(publishing): clean up from debugging artifact registry publishing

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

shared:
- GHA doesn't have a repository name env var like `clouddriver` so
add a step to extract the name from `spinnaker/clouddriver`
- Change build step to create installation distribution for use in
following container image build steps.
- add Alpine/slim container build step
- add Ubuntu container build step
when open PR has commit pushed to fork's branch:
- build only and don't push
- `latest{-slim|ubuntu}`
- `{git-SHA}-{DATE-TIME}{-slim|ubuntu}`
- validates gradle build, unit tests pass and Dockerfile's build
when commit pushed to specific branches (eg: merge PR):
- build and push with branch tags:
- `master` -> `master-latest-unvalidated-{slim|ubuntu}`
- `master` -> `master-{git-SHA}-{DATE-TIME}-unvalidated-{slim|ubuntu}`
- `release-*` -> …

chore(ci): GHA - container image build & push

---

.github/workflows/build.yml

https://github.com/kskewes/rosco/runs/5491186233?check_suite_focus=true#step:7:1
This fixes putting branch name, eg: `master` into the container tag - `us-docker.pkg.dev/spinnaker-community/docker/rosco:master-latest-unvalidated`
GHA output from merging this PR to my fork (with spinnaker org only and push disabled).
```
Run docker/build-push-action@v2
Docker info
/usr/bin/docker buildx build --file Dockerfile.slim --iidfile /tmp/docker-build-push-TbWVCS/iidfile --tag us-docker.pkg.dev/spinnaker-community/docker/rosco:master-latest-unvalidated --tag us-docker.pkg.dev/spinnaker-community/docker/rosco:master-740ddea487ee3bc0ae5d9b9bbe7e16c5d5d40569-202203100526-unvalidated --tag us-docker.pkg.dev/spinnaker-community/docker/rosco:master-latest-unvalidated-slim --tag …
```

fix(ci): GHA - use correct env var from context

---

.github/workflows/build.yml
.github/workflows/release.yml

We need to login in order to push to GAR and only specific `spinnaker`
org repositories have permission to do so.

fix(ci): GHA login to GAR and build+push for key branches

---

halconfig/rosco.yml

Otherwise Rosco tries and fails to connect to code fallback of
redis://localhost:6379
Tested in Halyard with a custom BOM and halconfigs.
```
2022-04-26 00:32:12.895 ERROR 1 --- [RxIoScheduler-2] c.n.spinnaker.rosco.executor.BakePoller  : Update Polling Error:
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
<snip>
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
```

fix(halyard): Use Halyard's spinnaker.yml defined Redis

---

rosco-core/rosco-core.gradle
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ServiceConfig.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java
rosco-web/rosco-web.gradle
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/WebConfig.groovy
rosco-web/src/test/java/com/netflix/spinnaker/rosco/controllers/V2BakeryControllerWithClouddriverServiceTest.java
rosco-web/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This is an improvement on https://github.com/spinnaker/rosco/pull/748, and facilitates troubleshooting by getting e.g. X-SPINNAKER-EXECUTION-ID into the MDC and therefore log messages.  In other words it's possible to correlate more log messages with a pipeline execution now.

fix(bake): propagate X-SPINNAKER-* headers to clouddriver

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.slim
Dockerfile.ubuntu

Changes that allow building Rosco images for both amd64 and arm64 architectures.  That's the first of many PRs to various Spinnaker Components that allow building docker images for multiple architectures.
Motivation:
Allow running & experimenting with Spinnaker locally on Macbok M1.
Changes:
- Choose binaries in docker build based on the target architecture
- bump Kustomize to a version that contains arm64 binaries
- update Github action to build multiple architectures

Arm64 support

---

.github/workflows/build.yml
.github/workflows/release.yml

A follow-up to https://github.com/spinnaker/rosco/pull/886 that fixes Github actions builds
Remove duplicate setup-java actions without proper config

chore(builds): fix github actions builds

---

.github/workflows/codeql-analysis.yml

see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

chore(security): upgrade codeql to v2

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore(gha): replace deprecated set-output and save-state commands

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy

By adding these fields to the bake key, it will enable concurrent bakes when selecting a different image, base label or base name. 
Resolves https://github.com/spinnaker/spinnaker/issues/6738

feat(azure): Improve uniqueness of Azure Bake Key

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/util/AzureImageNameFactory.java
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/util/AzureImageNameFactorySpec.groovy

Previously for azure, it was using the class `ImageNameFactory`, that class is written in groovy and it was removing empty params
Fixes spinnaker/spinnaker#6753

fix(azure): removing empty params for image name

---

rosco-manifests/rosco-manifests.gradle

Spring boot 2.4.13 brings in version 1.27 of org.yaml:snakeyaml (see https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom) which takes precendence over what we specified here (1.25), so there's no functional change.  See these snippets of ./gradlew rosco-manifests:dependencies before
```
+--- org.yaml:snakeyaml:1.25 -> 1.27
```
and after this change:
```
+--- org.yaml:snakeyaml -> 1.27
```

chore(deps): remove version specification from org.yaml:snakeyaml

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/DeleteBakesRequest.java
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/BakeStore.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/RedisBackedBakeStore.groovy
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy

**Description**
Rosco service uses Redis for caching purposes. The records created in Redis can be up to 50MB size and will never be removed. As a result, Redis can become quite expensive. This pull request changes solve this issue.

feat(bakery): Clean up cached data created by Rosco.

---

rosco-web/rosco-web.gradle

The property spring.config.additional-location is redundant in rosco-web.gradle file. This property is set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.rosco.Main. So removing it from gradle file.

refactor(web): Clean up redundant spring property in gradle file

---

rosco-core/rosco-core.gradle
rosco-manifests/rosco-manifests.gradle
rosco-web/rosco-web.gradle

with a specific goal to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.

chore(dependencies): remove dependency on groovy-all where straightforward

---

rosco-manifests/rosco-manifests.gradle

Since groovy is introduced by rosco-core project in rosco-manifest.gradle, so removing the dependency.
```
$ ./gradlew rosco-manifest:dI --dependency groovy
> Task :rosco-manifests:dependencyInsight
org.codehaus.groovy:groovy:2.5.15
variant "compile" [
org.gradle.status              = release (not requested)
org.gradle.usage               = java-api
org.gradle.libraryelements     = jar (compatible with: classes+resources)
org.gradle.category            = library
Requested attributes not found in the selected variant:
org.gradle.dependency.bundling = external
org.gradle.jvm.version         = 11
]
Selection reasons:
- By constraint
- Forced
org.codehaus.groovy:groovy:2.5.15
\--- io.spinnaker.kork:kork-bom:7.165.0
\--- compileClasspath
org.codehaus.groovy:groovy -> 2.5.15
\--- project …
```

chore(dependencies): remove residual dependency on groovy-all in rosco-manifest

---

build.gradle
rosco-manifests/rosco-manifests.gradle
rosco-web/rosco-web.gradle

Spring boot 2.4.x removed JUnit5 vintage engine from [spring-boot-starter-test](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test). It is required for executing junit4 based test cases in rosco. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 217 to 252 test case executions.

fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 in rosco

---

rosco-manifests/rosco-manifests.gradle

so junit5 tests run.  Before this PR, 9 tests ran in rosco-manifests, all spock tests.  After this PR, 32 tests run.
Before:
After:
Note that spring-boot-starter-test brings in org.junit.jupiter:junit-jupiter-engine so where that's used, we don't need to declare junit-jupiter-engine explicitly.  Note also that rosco-core currently only has spock tests, so although it doesn't use spring-boot-starter-test, it doesn't need org.junit.jupiter:junit-jupiter-engine either.

fix(manifests/test): add org.junit.jupiter:junit-jupiter-engine as a test runtime dependency

---

.github/workflows/release.yml

see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context for documentation of `github.ref` vs. `github.ref_name`

fix(gha): remove refs/tags from github release names

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pr.yml
.github/workflows/release.yml

and to remove warnings like:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
from e.g. https://github.com/spinnaker/rosco/actions/runs/4568371280

chore(gha): use checkout@v3 to stay up to date

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java

Uses the newInstance method on the SpinnakerException to clean up some exception handling in ArtifactDownloaderImpl.
The newInstance changes come from https://github.com/spinnaker/kork/pull/1046

refactor(manifests): use new methods in manifest exception handling

---

rosco-manifests/rosco-manifests.gradle
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImplTest.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/BakeManifestEnvironmentTest.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/cloudfoundry/CloudFoundryBakeManifestServiceTest.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java

Before refactor, total test cases executed were 275. 
After refactor, total test cases executed are 275.

refactor(tests): convert junit4 based testcases to junit5 and clean up in rosco

---

rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helmfile/HelmfileTemplateUtilsTest.java

Before refactor, total test cases executed were 275. 
After refactor, total test cases executed are 275.

refactor(tests): convert leftout junit4 based testcases to junit5

---

rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy

since https://github.com/spinnaker/kork/pull/1120 removes the artifact-store.enabled property such that ArtifactStore beans are always present.

chore(artifacts): always configure artifact store-related beans

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.slim
build.gradle
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocalSpec.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandlerSpec.groovy
rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy

Number 8 on our Java 17 adventure.
See also https://github.com/spinnaker/orca/pull/4604 etc

feat(java17): use JRE17, run tests on JRE17, compile with JDK11

---

rosco-web/src/test/java/com/netflix/spinnaker/rosco/controllers/V2BakeryControllerTest.java

since it's not necessary for the test, and can run if the test takes a long time.  It attempts to connect to redis which fails, and the exceptions/log messages muddy the test results.

chore(web/test): disable BakePoller in V2BakeryControllerTest

---

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/HelmBakeTemplateUtils.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helmfile/HelmfileTemplateUtils.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java
rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helmfile/HelmfileTemplateUtilsTest.java

This commit updates the Helm util helpers that we have to include the
artifact store. This will allow us to inspect the raw strings and check
to see if we need to expand them.
Further, I opted to not utilize the deserializer this time, since this
problem seemed very specific to Helm. If that changes, we can always
just use the deserializer
Signed-off-by: benjamin-j-powell <bjp@apple.com>

feat(artifact): Introduces the expansion of artifact store references in parameters 

---

Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.slim
Dockerfile.ubuntu
rosco-web/pkg_scripts/postInstall.sh

This PR upgrades Packer to version v1.10.1. All the previously default providers were [moved to plugins in v1.10][1], so we also need to manually install plugins. I've opted to install Amazon, Azure and Google plugins by default, but the list can be overridden by Docker build args (or an environment variable in the case of the deb package).
This PR also installs AWS CLI 2 and the Session Manager Plugin in the Ubuntu images and in the deb package. **I opted to not install it in the Alpine images**, as the session-manager-plugin is not officially supported, and you'd need to either copy the binary or compile it from source to get it to work. I'm very open to reconsider this.
After applying this PR, you can use [SSM instead of SSH][2] to connect to instances when baking using the …

feat(aws): Upgrade packer and add SSM support (Amazon)

---

build.gradle
rosco-core/rosco-core.gradle
rosco-manifests/rosco-manifests.gradle

Centralize lombok dependencies to remove duplication.  Also add a testCompileOnly dependency to make lombok available to test code and to follow https://projectlombok.org/setup/gradle.
Use enforcedPlatform with kork-bom since it really is supposed to determine what versions of dependencies to use.  This also matches what [clouddriver](https://github.com/spinnaker/clouddriver/blob/3f31190d40419218fd1d31ca78bb1661f1ef881a/build.gradle) does.
No differences in the output of:
```
alias gradle-all-deps='./gradlew --no-parallel --stacktrace dependencies $(./gradlew -q projects \
| grep -Fe ---\ Project \
| sed -Ee "s/^.+--- Project '"'([^']+)'/\1:dependencies/"'" | sort)'
```

centralize lombok dependencies in build.gradle and use enforcedPlatform with kork-bom

---

rosco-core/rosco-core.gradle
rosco-core/src/test/java/com/netflix/spinnaker/rosco/providers/aws/AWSStartupTest.java
rosco-core/src/test/java/com/netflix/spinnaker/rosco/providers/azure/AzureStartupTest.java
rosco-core/src/test/java/com/netflix/spinnaker/rosco/providers/docker/DockerStartupTest.java
rosco-core/src/test/java/com/netflix/spinnaker/rosco/providers/google/GCEStartupTest.java
rosco-core/src/test/java/com/netflix/spinnaker/rosco/providers/oracle/OracleStartupTest.java

Adding tests for AWS, Azure, Docker, Google and Oracle cloud providers to verify the rosco startup with these providers enabled.

test(core): add tests to verify the rosco startup with various cloud providers enabled

---

rosco-web/pkg_scripts/postInstall.sh

This attempt to fix the packer version check , which on failing would trigger a new download even if the same packer version is correctly insatalled.
This is an issue where packer for the arch type does not exists ( 404 ), eg. vm, docker images etc.
```
--2024-11-12 07:45:06--  https://releases.hashicorp.com/packer/1.10.1/packer_1.10.1_linux_.zip
Resolving releases.hashicorp.com (releases.hashicorp.com)... 99.86.20.99, 99.86.20.59, 99.86.20.95, ...
Connecting to releases.hashicorp.com (releases.hashicorp.com)|99.86.20.99|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-12 07:45:07 ERROR 404: Not Found.
```
packer version output format
```
himanshu@ubuntu-vm:~$ /usr/bin/packer  --version
Packer v1.10.1
Your version of Packer is out of date! The latest …
```

fix(install): fix packer version check in post install script.

---

rosco-web/pkg_scripts/postInstall.sh

Fixes the following error during post installation of the Rosco debian package:
```
Unpacking spinnaker-rosco (1.22.0) over (1.21.0) ...
Setting up spinnaker-rosco (1.22.0) ...
/var/lib/dpkg/info/spinnaker-rosco.postinst: 53: Syntax error: redirection unexpected
dpkg: error processing package spinnaker-rosco (--configure):
```

fix(install): Fixed packer version check for packer installation

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy

Fixes issue https://github.com/spinnaker/spinnaker/issues/6982

fix(gceBakeHandler): Updating Image name pattern to match googlecompute pre/post 1.1.2 plugin

---

gradle.properties
rosco-core/rosco-core.gradle
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/Bake.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy
rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeStatus.groovy
rosco-web/rosco-web.gradle
rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy

Depends on https://github.com/spinnaker/kork/pull/1198

fix(openapi): Rewrite Swagger to OpenAPI annotations

---

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy
rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocalSpec.groovy

in the BakeStatus that JobExecutorLocal.updateStatus returns.
Before this change, if the output of e.g. helm template is an empty string, the BakeStatus object that JobExecutorLocal.updateStatus returns is null, and HelmTemplateUtils.removeTestsDirectoryTemplates throws a NullPointerException.
HelmBakeManifestService.bake calls BakeManifestService.doBake which calls JobExecutorLocal.updateStatus, and then HelmBakeManifestService.bake calls HelmTemplateUtils.removeTestsDirectoryTemplates with the resulting String.
With this change, removeTestsDirectoryTemplates gets an empty string, and so the bake manifest endpoint (e.g. POST /api/v2/manifest/bake/helm) returns an empty Artifact.
Note that there's no Bake Manifest YAML link in bake manifest stages with empty bakes, but this still feels …

fix(core): prevent null outputContent
