spinnaker/rosco

rosco-web/pkg_scripts/preInstall.sh, rosco-web/rosco-web.gradle
This is in regards to https://github.com/spinnaker/spinnaker/issues/625 and should help with the issue I had when I updated the ubuntu package and our customer install_packages.sh was deleted.
=> backup install_packages.sh before installing

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeOptions.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/config/RoscoAWSConfiguration.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/docker/config/RoscoDockerConfiguration.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/config/RoscoGoogleConfiguration.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/registry/CloudProviderBakeHandlerRegistry.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/registry/DefaultCloudProviderBakeHandlerRegistry.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactory.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/ImageNameFactory.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverter.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactorySpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverterSpec.groovy, rosco-web/config/rosco.yml, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy, rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy
Cherry-pick @ttomsu's commit from #48.
Needed rebasing but I don't have write permissions to the forked repo.
=> First step in exposing customizable Bake options: exposing them in Rosco

rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy, rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy
Orca needs to be able to dynamically figure out the packageType for the specified base OS. This PR exposes the baseImage object endpoint.
@duftler @lwander PTAL
=> Adds detailed view of base Images to be used in Orca

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-web/config/packer/aws-ebs.json, rosco-web/config/packer/gce.json, rosco-web/config/packer/install_packages.sh
Run upgrades on the ami if you send upgrade with value true to api.
=> upgrade support

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy, rosco-web/config/packer/aws-ebs.json, rosco-web/config/packer/docker.json, rosco-web/config/packer/gce.json, rosco-web/config/packer/install_packages.sh, rosco-web/config/rosco.yml
This patch introduces the RPM support in Rosco.
=> Add RPM Support

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactory.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/docker/DockerBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactorySpec.groovy, rosco-web/config/packer/aws-ebs.json, rosco-web/config/packer/gce.json, rosco-web/config/packer/install_packages.sh
Use elvis-operator in one spot.
=> Minor formatting tweaks.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-web/config/packer/aws-chroot.json
This adds support for amazon-chroot builder
=> amazon chroot builder support

rosco-web/etc/init/rosco.conf
this change works together with PR by @ewiseblatt
https://github.com/spinnaker/spinnaker/pull/784
=> auto start rosco service if rosco is installed standalone, issue #762

rosco-web/config/packer/aws-ebs.json, rosco-web/config/packer/gce.json, rosco-web/config/packer/install_packages.sh
Configure ssh pseudo terminal to avoid 'sudo needs tty' error on centos.
=> Use sudo to run yum in packer templates.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactory.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/DefaultImageNameFactorySpec.groovy
@duftler please review, thanks :)
=> using apropriate version delimiter for rpm packages for baking

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/config/RoscoAzureConfiguration.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy, rosco-web/config/packer/azure-linux.json, rosco-web/config/rosco.yml, rosco-web/rosco-web.gradle, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
This is the initial commit for azure packer/bake support. It ads the initial steps of retrieving bakeOptions data from config data and supplying a template and log parsing.
@duftler PTAL
=> Initial commit for retrieving Azure config values.

rosco-web/config/packer/gce.json
=> provider/google: Increase state_timeout.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/JobRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandler.groovy, rosco-web/config/packer/openstack-v2.json, rosco-web/config/packer/openstack-v3.json, rosco-web/config/rosco.yml, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy
Also:
* filter openstack passwords in packer logs
* support v2 and v3 openstack packer templates
=> Add openstack metadata to image build

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/openstack/config/RoscoOpenstackConfiguration.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy, rosco-web/config/packer/openstack.json, rosco-web/config/rosco.yml
Added network option and renamed other to match configs for
clouddriver.
=> Updated openstack config options.

Dockerfile
@lwander I didnt test this, but I did test the packer version on GCE via InstallSpinnaker.
If you feel this change should be tested, could you give it a whirl?
=> Moved packer to 10.2

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandlerSpec.groovy
@lwander or @jtk54 please review.
=> (google) Support specifying an account name on the bake request.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/openstack/OpenstackBakeHandlerSpec.groovy
Helps prevent bakes with different files stomp on each other.
=> Adding template & var file names to bake keys.

halconfig/rosco.yml
=> Base rosco halconfig

build.gradle
@duftler 
I only need to bump to 0.68 for spectator change, but head is at 75 so I'm going there.
=> Bump spinnaker-dependencies.

Dockerfile, Dockerfile.slim, build.gradle, cloudbuild.yaml
=> Slim container & spinnaker gradle project bump

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandler.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/azure/AzureBakeHandlerSpec.groovy
While testing bake-only pipelines, I noticed that the image name in Azure always had a prefix of "null-null". This is due to 'build_number' and 'base_name' not being defined. This PR will use the 'imageName' passed into the 'buildParameterMap' method if the 'build_number' and 'base_name' are not defined. It also ensures that the generated 'azure_image_name', which is passed to packer as 'capture_name_prefix', meets the packer naming standard for this field. 
The packer code defines a [regex](https://github.com/mitchellh/packer/blob/master/builder/azure/arm/config.go#L45) that limits the character set to alphanumeric characters, underscore, dash, and period. The value can also not exceed 23 characters, nor end with a period or dash.
=> (Azure) Ensure 'azure_image_name' conforms to CaptureNamePrefix regex in packer

cloudbuild.yaml
=> GCB tag latest

rosco-web/config/packer/azure-linux.json
@scotmoor, @robumberger, @duftler PTAL
=> Fix to provisioning.  Adding removal fo waagent at end of bake.

halconfig/rosco.yml
=> (halconfig) fix redis connection

rosco-web/pkg_scripts/postInstall.sh, rosco-web/rosco-web.gradle
Closes https://github.com/spinnaker/spinnaker/issues/1462 :alien:
=> feat(build): Add 'unzip' as dependency, remove apt from postInst.

build.gradle, rosco-web/rosco-web.gradle, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/BakeryController.groovy, rosco-web/src/test/groovy/com/netflix/spinnaker/rosco/controllers/BakeryControllerSpec.groovy
I ended up merging the `lookupLogsJson` method because Swagger caused a startup issue with the other method with the same request mapping signature. Please confirm this will work as expected.
Merging into `boot-upgrade` branch
=> chore(springBoot): Upgrade to Spring Boot 1.5.4

rosco-web/rosco-web.gradle
Similar to buildDeb, we should also require unzip for buildRpm.
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features …
=> chore(gradle) Update buildRpm task to require unzip

rosco-web/config/packer/aws-ebs.json
We have needed more time in some cases
We prefer small, well tested pull requests.
Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).
When filling out a pull request, please consider the following:
* Follow the commit message conventions [found here](http://www.spinnaker.io/v1.0/docs/how-to-submit-a-patch).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.
Note that we are unlikely to accept pull requests that add features without prior discussion. …
=> fix(rosco) Make pause_before configurable, maintaining current default

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy, rosco-web/config/packer/aws-chroot.json, rosco-web/config/packer/aws-ebs.json, rosco-web/config/packer/aws-multi-chroot.json, rosco-web/config/packer/aws-multi-ebs.json, rosco-web/config/packer/aws-windows-2012-r2.json
@duftler 
This is new PR of https://github.com/spinnaker/rosco/pull/225
refs https://github.com/spinnaker/spinnaker/issues/2065
=> Fix aws enhanced networking backwards incompatibities 2

rosco-web/lib/systemd/system/rosco.service
Add systemd service config for Rosco.
=> feat(xenial_builds): Add systemd service configuration for rosco.

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
https://github.com/spinnaker/spinnaker/issues/2636
=> feat(bake/manifest): support helm `--set` overrides

rosco-manifests/rosco-manifests.gradle, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestService.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java
https://github.com/spinnaker/spinnaker/issues/2636
=> fix(bake/manifests): delete templates when request finishes

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/CloudProviderBakeHandler.groovy
Currently, when baking artifacts the resulting we get a generic
image name that does not reference the baked package.  Use the
'name' field of the artifact to construct the image name in the
same way that we use the 'package' string for non-artifact packages.
=> fix(artifacts): Use artifact name to construct package name

Dockerfile
=> chore(Dockerfile): Fix packer url.

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/V2BakeryController.java
This patch adds support passing namespace for Helm bakery.
link: spinnaker/spinnaker#2763
=> feat(bake/manifests): Add namespace support for Helm bakery

rosco-web/config/packer/install_packages.sh
Adds back the ability to supply multiple repos
=> fix(install_packages): support for multiple repos

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/google/GCEBakeHandler.groovy
We initialize the rosco GCE configuration at first read, but don't properly guard against concurrent requests. This means that sending a few concurrent requests to get the configuration shortly after rosco startup will cause some of those reuqests to return a partly-initialized configuration.
=> fix(google): Fix race condition in rosco config

rosco-web/pkg_scripts/postInstall.sh
Cherry pick of @ikemonn's fix into 1.9
=> chore(packer):  upgrade packer binary to 1.2.2 (#271)

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandler.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/ManagedOracleAccount.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/OracleBakeryDefaults.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/OracleConfigurationProperties.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/OracleOperatingSystemVirtualizationSettings.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/OracleVirtualizationSettings.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/RoscoOracleConfiguration.java, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandlerSpec.groovy, rosco-web/config/packer/oci.json, rosco-web/rosco-web.gradle, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
Adding bakery capability to the oracle provider.
See also https://github.com/spinnaker/halyard/pull/1011, https://github.com/spinnaker/orca/pull/2405, and https://github.com/spinnaker/deck/pull/5697.
=> feat(bake/oracle): Added oracle OCI bakery

rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java
issue: https://github.com/spinnaker/spinnaker/issues/3108
this patch depends on: https://github.com/spinnaker/orca/pull/2402
=> feat(bake/manifests): use custom output artifact name in helm bakery

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandler.java, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandlerSpec.groovy
Scrape the oracle bake result for additional image id.
=> fix(bake/oracle): scrape image id as well as name.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeStatus.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/jobs/local/JobExecutorLocal.groovy, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java
=> Revert "fix(bake/manifests): capture onny stdout in Helm bakery"

halconfig/images.yml, rosco-web/config/rosco.yml
Update the pre-defined VM image list for Azure Provider
- Ubuntu 16.04
- Ubuntu 18.04
=> feat(provider/azure): Update Azure VM image list

gradle/init-publish.gradle
https://github.com/spinnaker/spinnaker/issues/3997
=> fix(build): make gradle use https

.gitignore
=> chore(.gitignore): Update .gitignore

rosco-web/rosco-web.gradle
Prereq for spinnaker/kork#273 merge
=> chore(dependencies): ensure direct dependency on kork-secrets-aws

build.gradle, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoPackerConfigurationProperties.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/OCIBakeHandler.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/oracle/config/RoscoOracleConfiguration.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageNameConverter.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackageUtil.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackerArtifactService.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackerManifest.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/PackerManifestService.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/DebPackageUtil.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/util/packagespecific/RpmPackageUtil.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ClouddriverService.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/services/ServiceConfig.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/TemplateUtils.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmBakeManifestService.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/controllers/V2BakeryController.java
Enable codestyle enforcement on all subprojects and commit the results of spotlessApply.
=> chore(*): Apply codestyles

.travis.yml
This issue popped up in spinnaker/spinnaker as well, https://github.com/spinnaker/spinnaker/pull/4730
=> fix(buildtool): Set trusty dist for travis

Dockerfile.slim, Dockerfile.ubuntu, rosco-web/pkg_scripts/postInstall.sh
Updating packer version to support/fix the azure-arm unexpected EOF errors during packer buildout. 
[#5032](https://github.com/spinnaker/spinnaker/issues/5032)
=> fix(rosco): Update packer version in rosco

README.md, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/api/BakeRequest.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/huaweicloud/HuaweiCloudBakeHandler.java, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/huaweicloud/config/RoscoHuaweiCloudConfiguration.java, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/huaweicloud/HuaweiCloudBakeHandlerSpec.groovy, rosco-web/config/packer/huaweicloud.json, rosco-web/config/rosco.yml, rosco-web/rosco-web.gradle, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
Relevant Spinnaker Issues: spinnaker/community#17
=> feat(provider/huaweicloud): Add Huawei Cloud bakery to build VM image

.mergify.yml
https://github.com/spinnaker/spinnaker/issues/5189
=> chore(mergify): Allow OSS approvers to auto-submit

gradle.properties, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/persistence/config/RedisConnectionInfo.groovy
Readying the code for the upcoming Spring Boot 2.2 update on kork.
=> chore(dependencies): Upgrade Spring Boot to 2.2.1

build.gradle, rosco-bom/rosco-bom.gradle, settings.gradle
This simplifies dependency resolution downstream and is modeled off of -> https://github.com/spinnaker/clouddriver/pull/3794
=> feat(rosco-bom): publish rosco-bom

rosco-core/rosco-core.gradle, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy
This PR makes Rosco pluggable, similar to spinnaker/clouddriver#4383
=> feat(plugins): plugin support for rosco

Dockerfile.java8, Dockerfile.slim, Dockerfile.ubuntu, Dockerfile.ubuntu-java8
feature(kustomize): upgraded kustomize from 3.3.0 to 3.8.1
Closes [Spinnaker#5713](https://github.com/spinnaker/spinnaker/issues/5713)
=> feature(kustomize): upgraded kustomize from 3.3.0 to 3.8.1

rosco-web/rosco-web.gradle
Supports customization of logging per other Spinnaker services.
Closes https://github.com/spinnaker/spinnaker/issues/6083 and comments in https://github.com/spinnaker/spinnaker/issues/4409
=> feat(rosco): Add logback to gradle

Dockerfile.slim, Dockerfile.ubuntu, halconfig/packer/aws-windows-2012-r2.json, rosco-web/pkg_scripts/postInstall.sh
And other fixes and features, see: https://github.com/hashicorp/packer/blob/master/CHANGELOG.md
Tested by building `Dockerfile.slim` image, running it then doing a multi-region bake with the same custom Packer json config file as was using with Packer 1.4.5.
Closes: https://github.com/spinnaker/spinnaker/issues/6235
=> feat(packer): Update version to support AWS assume_role

rosco-manifests/rosco-manifests.gradle, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImpl.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtils.java, rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/ArtifactDownloaderImplTest.java, rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/ManifestTestUtils.java, rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java, rosco-web/rosco-web.gradle, rosco-web/src/test/java/com/netflix/spinnaker/rosco/controllers/V2BakeryControllerTest.java
See https://github.com/spinnaker/spinnaker/issues/6572 for background.
=> Handle spinnaker http exception for helm artifacts

.github/workflows/release.yml
Files are almost a copy and paste
=> chore(ci): GHA - indentation consistency

Dockerfile.slim, Dockerfile.ubuntu, rosco-manifests/rosco-manifests.gradle, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/BakeManifestRequest.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/config/RoscoKustomizeConfigurationProperties.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeBakeManifestService.java, rosco-manifests/src/main/java/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeTemplateUtils.java, rosco-manifests/src/test/groovy/com/netflix/spinnaker/rosco/manifests/kustomize/KustomizeTemplateUtilsSpec.groovy, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
Add Kustomize 4 support, the backward compatibility with Kustomize 3 is saved.
=> feat(rosco): add Kustomize 4 support

rosco-manifests/rosco-manifests.gradle, rosco-web/rosco-web.gradle
This change makes the project compatible with Gradle 7
=> chore(build): Gradle 7 compatibility

rosco-web/config/rosco.yml
Centos 7.1 is no longer available for Azure
=> fix(Azure): Update centos default image version.

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandler.groovy, rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/providers/aws/config/RoscoAWSConfiguration.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/aws/AWSBakeHandlerSpec.groovy, rosco-core/src/test/groovy/com/netflix/spinnaker/rosco/providers/util/LocalJobFriendlyPackerCommandFactorySpec.groovy
Cherry pick of PR for 1.26 release.
=> fix(rosco): fixes masking on aws

.github/workflows/release.yml
introduced in https://github.com/spinnaker/rosco/pull/966
=> fix(gha): remove empty env block

rosco-core/src/main/groovy/com/netflix/spinnaker/rosco/config/RoscoConfiguration.groovy, rosco-web/src/main/groovy/com/netflix/spinnaker/rosco/Main.groovy
This commit adds artifact storage to rosco. When rosco sends a request out to any service, any embedded/base64 artifacts will be automatically stored.
=> feat(artifacts): Add ArtifactStore to rosco

rosco-manifests/src/test/java/com/netflix/spinnaker/rosco/manifests/helm/HelmTemplateUtilsTest.java
exceptionDownloading test originally added in https://github.com/spinnaker/rosco/pull/818.
=> fix(manifests/test): add missing @Test annotation

rosco-integration/rosco-integration.gradle
=> fix(integration): use test configurations for dependencies

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Dockerfile.compile, gradle.properties
Compile to Java 11 bytecode using JDK 17.
Reference: https://github.com/spinnaker/igor/pull/1198
=> chore(build): enable cross compilation plugin for Java 17

gradle.properties, rosco-remote/Dockerfile, rosco-remote/rosco-fargate-job-executor/docker/scripts/fargate-rosco-command-wrapper.sh, rosco-remote/rosco-fargate-job-executor/docker/scripts/unpack-job-context.js, rosco-remote/rosco-fargate-job-executor/rosco-fargate-job-executor.gradle, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/FargateJobExecutor.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/FargatePackerCommandFactory.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/VaultIamAuthRequestFactory.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/config/FargateJobExecutorConfiguration.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/model/FargateConfig.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/model/FargateVaultConfig.java, rosco-remote/rosco-fargate-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/fargate/model/VaultIamAuthRequest.java, rosco-remote/rosco-fargate-job-executor/src/test/groovy/io/armory/spinnaker/rosco/jobs/fargate/FargatePackerCommandFactorySpec.groovy, rosco-remote/rosco-fargate-job-executor/src/test/java/io/armory/spinnaker/rosco/jobs/fargate/FargateJobExecutorTest.java, rosco-remote/rosco-fargate-job-executor/src/test/java/io/armory/spinnaker/rosco/jobs/fargate/VaultIamAuthRequestFactoryTest.java, rosco-remote/rosco-k8s-job-executor/rosco-k8s-job-executor.gradle, rosco-remote/rosco-k8s-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/k8s/K8sJobExecutorConfiguration.java, rosco-remote/rosco-k8s-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/k8s/K8sRunJob.java, rosco-remote/rosco-k8s-job-executor/src/main/java/io/armory/spinnaker/rosco/jobs/k8s/K8sRunJobExecutor.java, settings.gradle
This is draft, and started.  Need to move a lot of things LIKE the package structures and such.  BUT starting this if there's community interest.
To note SOME Of the auth pieces used vault heavily which may not be of interest to OSS.
=> feat(remote): Contributing remote rosco bake code.  
